# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

env:
  - KDIR=/tmp/linux-5.2.14

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Attempt to use Ubuntu 16.04
dist: xenial
group: travis_latest

# Test build with only GCC for now
#- clang
compiler:
  - gcc

addons:
  apt:
    packages:
      - libmnl-dev
      - libelf-dev

install:
  - pushd /tmp
  - wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.2.14.tar.xz
  - tar xf linux-5.2.14.tar.xz
  - cd linux-5.2.14/
  - make tinyconfig
  - ./scripts/config -e BINFMT_ELF -e MODULES
  - make olddefconfig
  - make -j5
  - popd

script:
  - make
  - ./src/ubr -h

