# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

env:
  - KDIR=/tmp/linux-4.19.72

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Attempt to use Ubuntu 16.04
dist: xenial
group: travis_latest

# Test build with only GCC for now
#- clang
compiler:
  - gcc

addons:
  apt:
    packages:
      - libmnl-dev

install:
  - cd /tmp
  - wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.72.tar.xz
  - tar xf linux-4.19.72.tar.xz
  - cd -

script:
  - make
  - ./src/ubr -h

